### ISSUE TITLE
optimize layout

### ISSUE THREAD

**Issue by dadorner** [fact-project/shifthelper_webinterface#21]
when doing shift, I usually have several pages open - to fit also the shifthelper website more easily, it would be great to have a layout that is better readable in a small window
![snap24](https://cloud.githubusercontent.com/assets/17411597/21700732/3836cd1a-d3a2-11e6-9b26-79aa6fb34c88.png)
![snap23](https://cloud.githubusercontent.com/assets/17411597/21700733/38395d5a-d3a2-11e6-9032-abfdd511a4af.png)

**Comment by dneise** [comment]
I find this layout perfectly readable on a small display, such as a smart phone. 
It was made to be used on a smart phone after all ... 

But, everything can be improved, I guess. I just don't understand what exactly you mean.
Can you point out what exactly should be changed?

We could remove the big headline "FACT ShiftHelper Webinterface" as people usually know what they are looking at ... is it that what you mean? 

![2017-01-06-084625_1920x1080_scrot](https://cloud.githubusercontent.com/assets/8200858/21711012/a415ac96-d3ec-11e6-9701-eb6469b5db3e.png)

**Comment by dadorner** [comment]
when I look to the website with normal window size 
![snap30](https://cloud.githubusercontent.com/assets/17411597/21722708/144452e2-d42e-11e6-9ea2-b7c5ffc47ae7.png)
it seems that there are 5 columns: timestamp, name of alert, type of alert, some explanation, button
when I reduce the width of the window, I find it much more difficult to grab quickly the relevant information from the table at once glance 
![snap23](https://cloud.githubusercontent.com/assets/17411597/21722988/21cfede4-d42f-11e6-9fc9-6e72207468e6.png)
also the menu, when expanded (it is good that it is then collapsed to the button on the right), gets a bit bulky then with one line per button
![snap24](https://cloud.githubusercontent.com/assets/17411597/21723002/29d8b048-d42f-11e6-8039-31ee60e9462f.png)

I think the goal should be to display the information in a way that it's easy to get in one glance all relevant information
so one could think about the following: 
* is the date really needed? that depends whether only the alerts of the same night or also older alerts are displayed - this I don't know
how much back in time are alerts displayed? in case it is more than 24h, one could think about adding a line with the date at the point of change of date
* WARNING could be reduced to WARN
* either the name or the description could be removed - probably the name as this is probably more internal information (if needed, it could be displayed only in eg a debug-mode of the website) and could be confusing for new shifters
* keep the description short and clear, e.g. 'There is a shift at the moment and Main.js is not running.' -> 'Main.js is not running during data taking time.'  or 'Main.js not running during shift.'
* then for the layout, one could think about displaying timestamp, WARN and the button in a first and the description in a second line

this is just a rough idea and I don't know if it would look good, but I think it could help for a more compact display which is more easily interpretable also in a small window

**Comment by dneise** [comment]
The problem with this issue is: It is highly subjective. 

The developers have spend a lot of time working with this interface, they are using it on their smartphone or on their laptops. 

* Yes the complete date is needed, if people want to report about alerts in the logbook, they should be able to just copy paste it, or make a screen shot. If we leave out the date, they need to manually add the date as some kind of meta data, say as the filename to the screen shot or so.

Such manual actions are highly error prone, especially during the night.

**Comment by dneise** [comment]
> WARNING could be reduced to WARN

It could also be reduces to W ... but is this really a problem? However, there is no need to specify the level at all.  After all we mis-use the level to distinguish between alerts for shifters and for experts .. so by definition everything, which shows up in this list is a WARNING. 

And we are currently planning to use a different list for ERROR, so the experts get their own list ... 

So in the future, we can omit the WARNING completely, ... but not because the word is too long, but because this kind of information is not needed at all.

**Comment by dneise** [comment]
> either the name or the description could be removed - probably the name as this is probably more internal information (if needed, it could be displayed only in eg a debug-mode of the website) and could be confusing for new shifters

yes, they could be removed. The name is easier to use, if you want to refer to certain Alert. e.g. for logging in the logbook (date, checkname) would be quite sufficient to find a certain alert.

maybe we can let the text become a tooltip

**Comment by dneise** [comment]
> keep the description short and clear, e.g. 'There is a shift at the moment and Main.js is not running.' -> 'Main.js is not running during data taking time.' or 'Main.js not running during shift.'

If you'd like to change this, please open a PR in shifthelper and we have a look.
