### ISSUE TITLE
Use ssl for ldap authentication

### ISSUE THREAD

**Issue by maxnoe** [fact-project/shifthelper_webinterface#7]
We have to wait for Watz to finish the updates on La Palma

**Comment by dneise** [comment]
any news here? ... no complaints just asking

**Comment by maxnoe** [comment]
I wrote him an email a few days ago, he did not answer yet.

**Comment by dneise** [comment]
This seems to go nowhere. I will have to call him directly and if he has no time, I will have to try and do it myself. The problem is, I have no idea, what I need to do, and what the problem is. I can try and talk to the admins at ETH, maybe the know enough LDAP to help me out .. 

However it would be helpful, if you could provide a more verbose description for this task.

**Comment by maxnoe** [comment]
The problem is the setup on gate. The config needs to he adjusted so also ldaps is possible.

I have not looked into what changes this would require.

**Comment by maxnoe** [comment]
This problem got solved in #9
